import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/Footer/Footer";
import Header from "@/components/common/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-red-400 ${inter.className}`}>{children}</body>
    </html>
  );
}
